[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "5d4fb384b204c533284f6e10ba33026d33b3773c"
os = "macos"

    [[LibArchive.download]]
    sha256 = "df2e170fb700a8bbe69a70e3ba6584ae28ac656748256cd8b77da5c12a79ac0c"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.aarch64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "b1882be69c51ce4dbb1ec21bb0cede359326530c"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "f05507e5970b4947839204c6dd4897025e9fd1eb2b3f7b071f54613037fdcbde"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.aarch64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "8f86a22a6498eea043d9ed69784eb2da0249a28a"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "63ce360ed4e88b73e0cfea742927fc1590c0c7b9455ccd4e8ef696930660bdbc"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.aarch64-linux-musl.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "a786989b590ef7232e9dba35f1b56f4652b92ad6"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "57ab96873e5a14d3c0823ad43eb3e323f1e0894095ddaa5741419878454de7e1"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.aarch64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2b49f9f01e858436d321454a2764ddb645b13158"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "69c9c63c03cf2dbb7feeeded9cacc7f0650659589f92546f7918a40d15ae680a"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.armv6l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d912c8dee7a4a8932dd1142c1e5476f429b18fdd"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "8d893d5c121f0bba38e72a7d33887823b742a918e5bd758971d6fe73aec6618c"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.armv6l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "468da1a1eaa79da96907d7e6ae3a2fc4a404a3d0"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "aafffeff1392ece681639b1a0cacfe910904176d358dfb0bb0029b624c47dcd0"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.armv7l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "79bed91f458fc94149cfb6f34610989ed5011227"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "8b6e84aba09d07086ab2b41ab595226a6b599ac372d0e36bbc9b9e717441afdf"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.armv7l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "2075af2edad1ff316e225bd2d1063ec7263a6722"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "cf8610ad1e1056bd8d8f9cd0066b508fe338025f6b65b7419cf987d4e73bbef2"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.i686-linux-gnu.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "af7b82175b542774a8649024a80c1f28945092b8"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "563665cff0aecbb70ac3de86b5b274701f285b70a1b6ebdbe488e567e94c94a8"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.i686-linux-musl.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "f60fc03446f7cd739d5ca847da338478bfd5adef"
os = "windows"

    [[LibArchive.download]]
    sha256 = "c354999c1f31d5e40bd79dc2016a831290e04d181d6d211f4bef269fd9bcfd93"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.i686-w64-mingw32.tar.gz"
[[LibArchive]]
arch = "powerpc64le"
git-tree-sha1 = "07ba885cbc22bf32640c7b0be2dc85c4a5dca6da"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "590574f74dd19c62a8e78bcf2e2a4bbd080e0e76698c1dc5f80d3dd520b32c7f"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.powerpc64le-linux-gnu.tar.gz"
[[LibArchive]]
arch = "riscv64"
git-tree-sha1 = "7f78f4bbcb17770cb25f0e1e5dc52c1a8c586edc"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "87b94255316c1c65124188e43d372980241da910cc1d2b28ae1ab9295d20eb6f"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.riscv64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "70ba1607c822d3984d658d6b872f049104ee9291"
os = "macos"

    [[LibArchive.download]]
    sha256 = "54bc934d6988e6a74f1edfa5a0dd2969174232f365bffcba22c733d2578b7ff6"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.x86_64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "532d7917a40f96233f3fffa357f5100cf332958a"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "f8f6be1c0d84c2071d818c7935a8f568cedb65149c915d5775c25d1f762e3de6"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.x86_64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "ee69de093a837d938fd1d1da981fe83bf52dc1ac"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "3bd3f62a39c23f7b3a41cd3c9adc0c66f7066bbcfb5159997f9af937350f6fad"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.x86_64-linux-musl.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "13ebf27db3ff84ceb2766228fd81ba12dba6c177"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "c79a0c6f6ce02cd8b7b25a73421dc3f3d2ca606c4850d0cbbc86a7f969f58194"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.x86_64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "99aa13a3abcbb2e2283b817ddd4af6a99e21ff48"
os = "windows"

    [[LibArchive.download]]
    sha256 = "b351d2e8f1196283d1972a839e7d4f819b588c0bc1daed928588363d77b8c951"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.6+0/LibArchive.v3.8.6.x86_64-w64-mingw32.tar.gz"
