[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "ca048a34fee85816085a165cd0f8a83e837f90e4"
os = "macos"

    [[LibArchive.download]]
    sha256 = "a874e19029a613145e180113836dabbf1df652b3dfe085ef6b725831576bbee9"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.aarch64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "1e4ae7b7f6b118385bc933d5ad297f906fdf8b84"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "c043c26c7181f03476609ae97f687ee0413b868f10a22337757928f7a535ccbd"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.aarch64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "a8b1a7a1a65c29f0999796b8b71a0b0b8196f896"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "9364c8d509e9d6f3776e359c28b1c9b9ae5f8c687a16317159c6978c2c871893"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.aarch64-linux-musl.tar.gz"
[[LibArchive]]
arch = "aarch64"
git-tree-sha1 = "5d7b4b61977c914aa1aac9ee670dc9b29fc21abe"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "e8a11646b6f3a1d2d0bcae8c1100f9791f41942ffa1398d8005bb2cdc8cd0fd4"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.aarch64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "280f33c0e9453a9c9ccdbf36b59cecba396c7e87"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "5dd02e883be4c6c83b300becd423a0010d6ae919cf07e5003f6ea0d2425743f9"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.armv6l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a2e1800920bdc090071be6087a2a7f2a50ed1f99"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "dd3ccb0af9f9a24f4e056152150ddd721d9ff1c8bb9ceaf9dc8448ea70ed3110"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.armv6l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fad2c587a35dd63310fe747eda6d52494a335d19"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "ca2ab533fb346d559291be5d66a249db4c91aeed59dc39dc774aa730c6867724"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.armv7l-linux-gnueabihf.tar.gz"
[[LibArchive]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "96c310ef9af4ac02eaada42e66f91f657c6ce842"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "148b1d2bd164f60a32ea78fe525b4959c702005bca601b111974cedce331f00d"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.armv7l-linux-musleabihf.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "641cc82e9b9914dda1ed390981a8d618742db4f0"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "f262ab3f67d804a68fedd91b1e2d82e10da5c7f5acc108b428c4a8393fc374d3"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.i686-linux-gnu.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "83bb723e64f204bbdd3e0e89b0afbb7fde988a9c"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "9a3771f3f98e94dd92ebefead73e51522222378407e34d260473de8cc733052c"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.i686-linux-musl.tar.gz"
[[LibArchive]]
arch = "i686"
git-tree-sha1 = "ea12ac3490d1c417d2260a4398a3ce2347dcf0b5"
os = "windows"

    [[LibArchive.download]]
    sha256 = "76e3cfd2f5f51b4f26ee25a8cce4ddb797da862df66db8a4ef7d8769e37d9e8f"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.i686-w64-mingw32.tar.gz"
[[LibArchive]]
arch = "powerpc64le"
git-tree-sha1 = "dba1ffc0d8074e3b02156d2fb748ab18295f10d1"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "0c527d8d53cbcca4d7fc397a03e7518f5908c42bc8e8af271702a26db4489326"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.powerpc64le-linux-gnu.tar.gz"
[[LibArchive]]
arch = "riscv64"
git-tree-sha1 = "bfe3915b28c7756e5c429ba8b0f9121e5478796e"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "55815b6017177c71f1d26c8772d6d84ba93f0f58d7d3c77b873de5bf420e2811"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.riscv64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "74d411bb601e5d1b2269dbabbb5bf73cb8761b71"
os = "macos"

    [[LibArchive.download]]
    sha256 = "cdd6edfca3d34e66fd357d065dd710102bcf644279b28d920991850d38c8d64c"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.x86_64-apple-darwin.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "08717a98ad77ee82132e54b643fb6516a92975ad"
libc = "glibc"
os = "linux"

    [[LibArchive.download]]
    sha256 = "d99af52f50ec0208989b5fab79ab3235003df4090a9f306046d71af8e195e087"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.x86_64-linux-gnu.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "5479c035672e48bb8cd087bd13e30c3cf4bd25c3"
libc = "musl"
os = "linux"

    [[LibArchive.download]]
    sha256 = "6599c4a9d8240713d25a5013d3f293fbc8da6299c76e50651f26471512a6b988"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.x86_64-linux-musl.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "741d8649fd05bcb02e38b587fbe1bf135dbb56e1"
os = "freebsd"

    [[LibArchive.download]]
    sha256 = "390e5e35bbc3ec95993f70d2088c6404ce10f78d733f550bf75f63109d7a0eb6"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.x86_64-unknown-freebsd.tar.gz"
[[LibArchive]]
arch = "x86_64"
git-tree-sha1 = "7afd3efdabf61ee520c7a44894073453a1d1bf09"
os = "windows"

    [[LibArchive.download]]
    sha256 = "1c4f1fc5f437ac427f5eb19e6b7d505120a7cdfe9d9eb458195421969b3b7e20"
    url = "https://github.com/JuliaBinaryWrappers/LibArchive_jll.jl/releases/download/LibArchive-v3.8.5+0/LibArchive.v3.8.5.x86_64-w64-mingw32.tar.gz"
